---
- name: Install masakari server
  hosts: masakari_all
  user: root
  roles:
    - { role: "os_masakari", tags: [ "os-masakari" ] }
  vars:
    external_lb_vip_address: 10.232.48.205
    internal_lb_vip_address: 172.29.236.100
    glance_galera_address: "{{ internal_lb_vip_address }}"

